### ISSUE TITLE
detect stream availability in sync

### ISSUE THREAD

**Issue by dai-shi** [devongovett/rsc-html-stream#1]
Hi, thanks for the nice library. I haven't decided if I try this, but one thing blocking for me is to check the availability of the stream synchronously.

Can it be done like this?
```diff
- export let rscStream = new ReadableStream({
+ export let rscStream = (typeof window === 'undefined' || !Array.isArray(window.__FLIGHT_DATA)) ? undefined : new ReadableStream({
    start(controller) {
-     if (typeof window === 'undefined' || !Array.isArray(window.__FLIGHT_DATA)) {
-       return;
-     }
```

Or, is flight data not yet ready at that point?

**Comment by devongovett** [comment]
Yeah, in theory it could be possible that the script with this library runs before the inline scripts that contain the RSC payload. Actually I should probably change it to define `window.__FLIGHT_DATA` if it is not available yet instead of returning early.

What's your use case for this? I guess another option could be to add a separate export for it.

**Comment by dai-shi** [comment]
My case can be tricky because of the code structure. The goal is to start fetching RSC payload immediately if no `window.__FLIGHT_DATA` is available. Maybe I can add another flag on my end `window.__IS_FLIGHT_DATA_AVAILABLE`, it's just hacky though.

**Comment by dai-shi** [comment]
I think I can solve it on my end.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/waku/pull/529 I ended up writing our own client side code.
